Remove calls to get `Account` from DA & EO
versatus/lasr pull request #180
Opened 2024-05-14 20:11 UTC by andrewvious

Closes #179 
Removed unused functions regarding the retrieval of `Account`'s via stale methods.
Updated logging to reflect changes

2024-05-14 20:31 UTC, eureka-cpu requested changes
Looking good so far. One thing we may want to do is also replace calls to `check_account_cache` with the `get_account` helper method.

2024-05-14 20:31 UTC, eureka-cpu commented on crates/actors/src/engine.rs
>              }
This no longer needs to be a conditional statement

2024-05-14 20:31 UTC, eureka-cpu commented on crates/actors/src/eo_client.rs
> +                todo!()
I think we can safely remove this message from `EoMessage` and subsequently from this `match` statement

2024-05-14 20:31 UTC, eureka-cpu commented on crates/actors/src/scheduler.rs
> +        if let None = check_account_cache(address).await {
this can just be an `else`, no need to make a second call to `check_account_cache`

2024-05-14 20:31 UTC, eureka-cpu commented on crates/actors/src/eo_client.rs
> -                guard.push(fut.boxed());
Does this need to be removed? We may still want to be able to get the account balance from EO. @ASmithOWL ?

2024-05-14 21:50 UTC, andrewvious commented on crates/actors/src/engine.rs
> -    async fn get_account(&self, address: &Address, account_type: AccountType) -> Account {
Should this extra logic regarding the `account_type` (which was not being used) be implemented into the `helpers::get_account()`?

2024-05-14 21:53 UTC, eureka-cpu commented on crates/actors/src/engine.rs
> -    async fn get_account(&self, address: &Address, account_type: AccountType) -> Account {
Seems to me that it was only necessary when we were deciding whether to look for the account in the DA. It can probably be removed.

2024-05-15 15:52 UTC, ASmithOWL commented on crates/actors/src/engine.rs
> -    async fn get_account(&self, address: &Address, account_type: AccountType) -> Account {
No, do not remove it, otherwise we will not be able to acquire program accounts, only the account for the owner of the program, we still need to check if it's a User or Program account, and if they'll latter we need to make sure we use the program address not the owner address.

Also I wouldn't remove the get_account_from_da wholesale, I'd replace it with a function that reads from TiKV instead of EO/DA.

2024-05-15 15:55 UTC, ASmithOWL commented on crates/actors/src/engine.rs
> -    async fn get_program_account(&self, account_type: AccountType) -> Result<Account, EngineError> {
This is still necessary.

2024-05-15 15:55 UTC, ASmithOWL commented on crates/actors/src/engine.rs
> -    async fn get_caller_account(&self, address: &Address) -> Result<Account, EngineError> {
This is still necessary

2024-05-15 15:55 UTC, ASmithOWL commented on crates/actors/src/eo_client.rs
> -                guard.push(fut.boxed());
We never need to acquire account balance from EO. When a user is bridging OUT of LASR the amount and token they're bridging out is determined and sent to the EO by LASR.

2024-05-15 15:55 UTC, ASmithOWL commented on crates/actors/src/helpers.rs
>      check_account_cache(address).await
We should add a function to read from TiKV here in the event check_account_cache returns None.

2024-05-15 15:55 UTC, ASmithOWL commented on crates/actors/src/helpers.rs
>      check_account_cache(address).await
And then we should use this function everywhere we need to get an account.

2024-05-15 16:01 UTC, andrewvious commented on crates/actors/src/helpers.rs
>      check_account_cache(address).await
Currently the `get_account()` in `helper.rs` contains all the logic of both account_cache & TiKV. I went with this route to avoid needing a widespread need for the TiKV client. If `check_account_cache` returns None, that would mean the account was not found in either the account_cache or the persistence layer.

2024-05-15 16:05 UTC, andrewvious commented on crates/actors/src/engine.rs
> -    async fn get_account(&self, address: &Address, account_type: AccountType) -> Account {
The function above wasn't being used anywhere, which is why I posed the question; Should we add this account_type filter to the `helpers::get_account()` which is being used anytime an Account needs to be pulled from the account_cache/persistence store

2024-05-15 16:12 UTC, andrewvious commented on crates/actors/src/helpers.rs
>      check_account_cache(address).await
https://github.com/versatus/lasr/blob/main/crates/actors/src/account_cache.rs#L226
This is where the logic gets handled, first it checks the `account_cache` if `None`, passes to TiKV, and if an account is found in TiKV it will write it to the account_cache, and then return the account. This step will speed things up, as the next time `get_account()` get's called it will be in the account_cache.

https://github.com/versatus/lasr/blob/main/crates/actors/src/helpers.rs#L345 
^ Added a note in an earlier PR explaining

2024-05-15 16:34 UTC, eureka-cpu commented on crates/actors/src/engine.rs
> -    async fn get_account(&self, address: &Address, account_type: AccountType) -> Account {
I would check if there are any other places that use the `AccountType` this way, if not, then it's probably better to leave this logic here in the engine

2024-05-15 16:38 UTC, eureka-cpu commented on crates/actors/src/engine.rs
> -    async fn get_account(&self, address: &Address, account_type: AccountType) -> Account {
> Also I wouldn't remove the get_account_from_da wholesale, I'd replace it with a function that reads from TiKV instead of EO/DA.

The `AccountCache` has a copy of the `TikvClient`, and the `Read` message will check the persistence if the `Address` and `Account` key value pair aren't in the cache. If it finds the account, it updates the cache for faster reads the next time the cache is read from. This also keeps the client in a singular place, as opposed to having the client live in every actor that needs to acquire an account using the `get_account` method.

2024-05-15 17:30 UTC, eureka-cpu commented on crates/actors/src/eo_client.rs
> -                guard.push(fut.boxed());
@andrewvious if you can go ahead and remove the message variant and the match arm for it here

2024-05-15 18:04 UTC, ASmithOWL approved these changes

2024-05-15 18:44 UTC, eureka-cpu approved these changes

2024-05-15 18:46 UTC, merged