Read container output from temp file instead of Std Out
versatus/lasr pull request #187
Opened 2024-05-17 14:30 UTC by mikehostetler

** This code hasn't been tested due to challenges with running `runsc` localy **

This code does the following:

1. Creates a temporary file based upon the container path and container id - ensures that file exists on disk - ensures the file is blank
2. Redirects the Command to execute `runsc` to dump its output to this temporary file
3. Reads the contents of the temporary file and returns them instead
4. Deletes the file after it has been used up

2024-05-17 15:34 UTC, eureka-cpu commented
Does this close #107 ?

2024-05-17 16:10 UTC, mikehostetler commented
Yes - this would close #107

2024-05-29 22:44 UTC, andrewvious requested changes
Everything seems to working as intended, here is the logging info I was able to get during testing:
```lasr   | 2024-05-29T22:13:59.983Z ERROR [lasr_compute::compute] Calling: runsc --rootless --network=none run -bundle ./containers/bafyreid6i4ych4otqzurhamkh3ep6d43dsn2ovlncdw32upmkc6rlabbb4 bafyreid6i4ych4otqzurhamkh3ep6d43dsn2ovlncdw32upmkc6rlabbb4
lasr   | 2024-05-29T22:13:59.985Z ERROR [lasr_compute::compute] temp file path established for std::out "/tmp/lasr/bafyreid6i4ych4otqzurhamkh3ep6d43dsn2ovlncdw32upmkc6rlabbb4.out"
lasr   | 2024-05-29T22:13:59.985Z ERROR [lasr_compute::compute] temp dir created: "/tmp/lasr"
lasr   | 2024-05-29T22:13:59.985Z ERROR [lasr_compute::compute] temp file not found, creating with tokio call: "/tmp/lasr/bafyreid6i4ych4otqzurhamkh3ep6d43dsn2ovlncdw32upmkc6rlabbb4.out"
lasr   | 2024-05-29T22:13:59.985Z ERROR [lasr_compute::compute] temp file created again? : "/tmp/lasr/bafyreid6i4ych4otqzurhamkh3ep6d43dsn2ovlncdw32upmkc6rlabbb4.out"
lasr   | 2024-05-29T22:13:59.986Z ERROR [lasr_compute::compute] passing inputs to stdio: "{lots of account/metadata, removed for sake of readability}"
lasr   | 2024-05-29T22:14:00.455Z ERROR [lasr_compute::compute] result from container: bafyreid6i4ych4otqzurhamkh3ep6d43dsn2ovlncdw32upmkc6rlabbb4 = "{\"computeInputs\":{lots of account/metadata, removed for sake of readability}"
lasr   | 2024-05-29T22:14:00.456Z ERROR [lasr_compute::compute] results received, informing executor
lasr   | 2024-05-29T22:14:00.456Z ERROR [lasr_compute::compute] casted message to inform executor
lasr   | 2024-05-29T22:14:00.456Z ERROR [lasr_compute::compute] cleaning up temp file...

2024-05-29 22:44 UTC, andrewvious commented on crates/compute/src/compute.rs
> +                let _ = tokio::fs::File::create(&temp_file_path).await?;
The first create file call using tokio can be removed, as it's handled with std in the following lines where it's being used for stdout redirection.

2024-05-31 05:17 UTC, eureka-cpu approved these changes

2024-05-31 15:34 UTC, merged