fix: stop duplicate eo event detection
versatus/lasr pull request #227
Opened 2024-06-20 19:19 UTC by mitch-vrrb

2024-06-20 19:55 UTC, andrewvious reviewed
Other than my comment, LGTM. Might also be helpful to add similar logging found in `increment_bridge_filter()` to `increment_blob_filter()`

2024-06-20 19:55 UTC, andrewvious commented on crates/eo_listener/src/lib.rs
> +            + 1;
Should this be `+ U64::from(1);` ?

2024-06-21 00:12 UTC, eureka-cpu requested changes
Was this solution tested on the box?

2024-06-21 00:12 UTC, eureka-cpu commented on crates/eo_listener/src/lib.rs
> +            .unwrap_or_else(|| &default)
`.unwrap_or_default()`

2024-06-21 00:12 UTC, eureka-cpu commented on crates/eo_listener/src/lib.rs
> +            .unwrap_or_else(|| &default)
Same here

2024-06-26 12:05 UTC, mitch-vrrb commented on crates/eo_listener/src/lib.rs
> +            .unwrap_or_else(|| &default)
unwrap or default fails to compile, I tried the change but this was done to avoid this error:

```
error[E0277]: the trait bound `&web3::types::U64: Default` is not satisfied
    --> crates/eo_listener/src/lib.rs:376:62
     |
376  |         let from_block = self.bridge_processed_blocks.last().unwrap_or_default() + U64::from(1);
     |                                                              ^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `&web3::types::U64`
     |
     = help: the trait `Default` is implemented for `web3::types::U64`
note: required by a bound in `std::option::Option::<T>::unwrap_or_default`
    --> /Users/mitchellmartin/.rustup/toolchains/1.75.0-aarch64-apple-darwin/lib/rustlib/src/rust/library/core/src/option.rs:1003:12
     |
1001 |     pub fn unwrap_or_default(self) -> T
     |            ----------------- required by a bound in this associated function
1002 |     where
1003 |         T: Default,
     |            ^^^^^^^ required by this bound in `Option::<T>::unwrap_or_default`
```

2024-06-26 12:06 UTC, mitch-vrrb commented on crates/eo_listener/src/lib.rs
> +            .unwrap_or_else(|| &default)
I ended up changing it to:

`
        let from_block = self.settled_processed_blocks.last().unwrap_or(&default) + U64::from(1);`

2024-06-26 12:06 UTC, mitch-vrrb commented on crates/eo_listener/src/lib.rs
> +            .unwrap_or_else(|| &default)
see above

2024-06-26 15:49 UTC, andrewvious approved these changes

2024-06-26 17:01 UTC, merged