Add clippy CI check to workflow
versatus/lasr pull request #99
Opened 2024-04-03 23:20 UTC by andrewvious

Closes #75 

The clippy check isn't currently passing, working on getting the warnings taken care of in a separate PR.

2024-06-14 18:04 UTC, andrewvious commented
There are only two clippy warnings left revolving around a `manual implementation of an assigned operation`.
These warning's can be handled in a separate PR need be @eureka-cpu @mitch-vrrb

2024-06-14 22:35 UTC, mitch-vrrb commented
Those clippy errors aren't warnings, this test overflows the stack:


```
#[cfg(test)]
mod test {
    #[test]
    fn test_u256_into() {
        let eth_u256: ethereum_types::U256 = ethereum_types::U256::one();

        let token_u256: &mut super::U256 = eth_u256.into();
        assert_eq!(eth_u256, token_u256.into());
    }
}
```

2024-06-16 06:09 UTC, eureka-cpu requested changes
Can you see if removing the recursive `From` implementations causes any failures? Left one other review comment, otherwise looks good.

2024-06-16 06:09 UTC, eureka-cpu commented on .github/workflows/rust.yml
> +          submodules: true
I think you can remove this

2024-06-17 08:22 UTC, eureka-cpu commented on .github/workflows/rust.yml
> +          args: --all-features --all-targets -- -D warnings
Seems it's having trouble finding the `Cargo.toml` file. Try adding `--workspace` to this and see if it fixes the failure.

2024-06-17 16:59 UTC, andrewvious commented on .github/workflows/rust.yml
> +          submodules: true
I added this chunk back, and clippy is able to find the `Cargo.toml` again.

2024-06-17 19:22 UTC, eureka-cpu commented on .github/workflows/rust.yml
> +          submodules: true
Try adding this instead, maybe it has to do with the fact we aren't installing a rust toolchain which might be required by the actions-rs clippy-check 
```
- name: Install toolchain
  uses: dsherret/rust-toolchain-file@v1
```

2024-06-17 23:42 UTC, merged